### ISSUE TITLE
Url is set to http even though it should be https

### ISSUE THREAD

**Issue by slurdge** [crazy-max/docker-anonaddy#1]
### Behaviour

The URL written by Laravel Framework are in http but they should be https.

### Configuration

docker-compose with a traefik.
Traefix has the following configuration:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=anonaddy"
      - "traefik.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.rule=Host:anonaddy.example.com"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Proto:https"
      - "traefik.frontend.headers.customResponseHeaders=Content-Security-Policy: upgrade-insecure-requests;"

The X-Forwarded-Proto is correctly forwarded too by nginx as far as I understand, however the app is missing an important config.

To fix it, I used the following command
```
 docker exec -it anonaddy php artisan vendor:publish
```
And activated the Fideloper\Proxy\TrustedProxyServiceProvider .
After that, I put "*" as acceptable IPs and cleared config&cache.

From that point, the URLs are correctly written as https.

**Comment by slurdge** [comment]
Here is the list of what's needed to have https:

```
docker exec -it anonaddy php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"
docker exec -it anonaddy sed -i "s/'proxies' => null/'proxies' => '*'/g" /var/www/anonaddy/config/trustedproxy.php
docker exec -it anonaddy php artisan config:clear
docker exec -it anonaddy php artisan cache:clear
```

**Comment by crazy-max** [comment]
@slurdge Should be fixed now, thanks!
