### ISSUE TITLE
Alias domain is empty

### ISSUE THREAD

**Issue by slurdge** [crazy-max/docker-anonaddy#2]
Not sure if this is due to dockerisation, but when creating a UUID alias, the field for alias domain is empty.

The domain is correctly set everywhere else. I didn't find the root cause yet.

![image](https://user-images.githubusercontent.com/1651201/71127285-174a5500-21eb-11ea-95ad-9e9b6042227f.png)

**Comment by crazy-max** [comment]
I suggest to open an issue on the [app repo](https://github.com/anonaddy/anonaddy) about this one.
