### ISSUE TITLE
Allow (and default to) sendmail as driver for sending email

### ISSUE THREAD

**Issue by slurdge** [crazy-max/docker-anonaddy#5]
Right now, the default (hardcoded) driver is smtp but it doesn't make sense since anonaddy is well able to send emails.

`MAIL_DRIVER` should be forwarded (as per the config.sh file) and also, should default to `sendmail`. By changing this, then the confirmation email could be sent.
Also, the `MAIL_FROM_ADDRESS`, if empty, could default to `anonaddy@{ANONADDY_HOSTNAME}` instead of example.com.

**Comment by crazy-max** [comment]
Done, thanks for your input!
