### ISSUE TITLE
Split the postfix+php from the nginx+php

### ISSUE THREAD

**Issue by slurdge** [crazy-max/docker-anonaddy#8]
Since the cron is already a separate container, we should separate the postfix container from the nginx one, since their only link is through the database.

It should be possible to add all the spamassassin etc. to the postfix one later.

**Comment by crazy-max** [comment]
@slurdge 

> since their only link is through the database.

Cannot do that since the app is closely linked to the app with `anonaddy:receive-email` cmd. See [Postfix master config](https://github.com/crazy-max/docker-anonaddy/blob/3274060ff625a0d1ba281233497ffc98225d0e24/rootfs/etc/cont-init.d/03-config.sh#L132-L138).

**Comment by crazy-max** [comment]
But maybe you think about a dedicated container for postfix with AnonAddy backend in it?

**Comment by slurdge** [comment]
Yes exactly, sorry for the imprecise wording.
