### ISSUE TITLE
Any way for anonaddy and mailcow to coexist?

### ISSUE THREAD

**Issue by homlett** [crazy-max/docker-anonaddy#9]
Hi there,

I'd be thrilled to host anonaddy on my own server thanks to your work. However, since I'm already hosting [mailcow](https://github.com/mailcow/mailcow-dockerized) and as smtp port cannot be shared, I guess I cannot, 

Would you think there might be a trick to manage that? Or a way to plug anonaddy with mailcow?

Thanks.

**Comment by crazy-max** [comment]
Hi @homlett, you should ask this question on the [official repository](https://github.com/anonaddy/anonaddy). I don't bring support directly related to anonaddy.

**Comment by homlett** [comment]
I know, but I though the solution could come through docker. Anyway, I'll ask. Thanks.

**Comment by crazy-max** [comment]
@homlett Don't think this is feasable without changes on AnonAddy.
